# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

auto_flatten <- function(inputPath, nCones, flattenToDisk, mapToSphere, normalizeUVs, outputPath) {
    invisible(.Call(`_rbff_auto_flatten`, inputPath, nCones, flattenToDisk, mapToSphere, normalizeUVs, outputPath))
}

flatten_to_shape <- function(inputPath, boundary_shape, normalizeUVs, outputPath) {
    invisible(.Call(`_rbff_flatten_to_shape`, inputPath, boundary_shape, normalizeUVs, outputPath))
}

